# Generated by Django 3.2.3 on 2021-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('name', models.CharField(choices=[('vegan', 'VG'), ('vegetarian', 'VT'), ('diabetic', 'DT'), ('all', 'AL')], help_text='Choose the nutrition style', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the the recipe', max_length=1000)),
                ('instruction', models.TextField(help_text='Enter instructions for the cooking recipe ; separated', max_length=1000)),
                ('ingredients', models.TextField(help_text='Enter ingredients for the cooking recipe ; separated', max_length=1000)),
            ],
        ),
    ]
