# Generated by Django 3.2.3 on 2021-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('art', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('art', models.CharField(max_length=20)),
                ('description', models.TextField(help_text='Enter a brief description of the the recipe', max_length=1000)),
                ('instruction', models.TextField(help_text='Enter instructions for the cooking recipe ; separated', max_length=1000)),
                ('ingredients', models.TextField(help_text='Enter instructions for the cooking recipe ; separated', max_length=1000)),
            ],
        ),
    ]
