# Generated by Django 3.2.3 on 2021-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.CharField(choices=[('VG', 'Vegan'), ('VT', 'Vegetarian'), ('DT', 'Diabeth'), ('AL', 'All')], help_text='Choose the nutrition style', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for nutrition style', max_length=10)),
            ],
        ),
    ]
