# Generated by Django 3.2.3 on 2021-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('art_id', models.ManyToManyField(help_text='Select an Art for cooking recipe', to='recipe.Art')),
            ],
        ),
    ]
