# Generated by Django 3.2.3 on 2021-05-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='art_id',
            field=models.ManyToManyField(help_text='Select an Art for the ingedient', to='recipe.Art'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the the recipe', max_length=1000)),
                ('instruction', models.TextField(help_text='Enter instructions for the cooking recipe ; separated', max_length=1000)),
                ('ingredients', models.TextField(help_text='Enter ingredients for the cooking recipe ; separated', max_length=1000)),
                ('art_id', models.ManyToManyField(help_text='Select an Art for cooking recipe', to='recipe.Art')),
                ('ingredient', models.ManyToManyField(help_text='Select an ingredient for cooking recipe', to='recipe.Ingredient')),
            ],
        ),
    ]
