# Generated by Django 3.2.3 on 2021-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210523_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.CharField(choices=[('VG', 'Vegan'), ('VT', 'Vegetarian'), ('DT', 'Diabetic'), ('AL', 'All')], help_text='Choose the nutrition style', max_length=2, primary_key=True, serialize=False),
        ),
    ]
