# Generated by Django 3.2.3 on 2021-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_art_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.CharField(help_text='Enter a description for nutrition style', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='description_src',
            field=models.URLField(help_text='Enter an url for the source of description', null=True),
        ),
    ]
