# Generated by Django 3.2.3 on 2021-06-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
