# Generated by Django 3.2.3 on 2021-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/%name'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_src',
            field=models.URLField(help_text='Enter an url for the source of recipe', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/%name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='art_id',
            field=models.ManyToManyField(help_text='Select an Art for the ingredient', to='recipe.Art'),
        ),
    ]
