# Generated by Django 3.2.3 on 2021-06-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20210612_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description_src',
            field=models.URLField(blank=True, help_text='Enter an url for the source of recipe', null=True),
        ),
    ]
