# Generated by Django 3.2.3 on 2021-06-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_recipe_description_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description_src',
            new_name='recipe_src',
        ),
    ]
